### PR TITLE
React native start project

### PR DESCRIPTION
**Pull request by paulSanchezMarmelab**
Just starting a blank project

### CODE REVIEW

**Review by fzaninotto — COMMENTED** [review]
Is it ready for review? If not, what' left to do?

**Comment by paulSanchezMarmelab** [comment]
Everything shall be fine and ready for review.

**Comment by adguernier** [comment]
except the CSS reformat that should not be in this commit in my opinion, it's OK for me

**Review by guilbill — APPROVED** [review]

**Comment by guilbill** [comment]
Just one more thing.  the make install command could be simpler, the `yarn install` is sufficient. no need to add the `yarn workspace ... install`, yarn workspace is designed to install the dependencies of all the workspaces by default

**Review by fzaninotto — APPROVED** [review]

**Pull request merged**
